# Generated by Django 6.0.5 on 2026-05-25 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingestion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='carbonledger',
            name='reversal_note',
            field=models.TextField(blank=True, help_text='Mandatory audit note when reversing an entry'),
        ),
    ]
